---
- name: Deploy local django app to remote Ubuntu server
  hosts: webservers
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Create app directory
      file:
        path: "{{ app_remote_path }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy app files to server
      copy:
        src: "{{ app_local_path }}/"
        dest: "{{ app_remote_path }}/"
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    # - name: Copy nginx configuration to server
    #   copy:
    #     src: "{{ nginx_conf_path }}"
    #     dest: "{{ nginx_conf_dest }}"
    #     owner: ubuntu
    #     group: ubuntu
    #     mode: '0755'

    - name: Install Django using pip
      shell: |
        python3 -m pip install --upgrade pip
        pip install django
      args:
        executable: /bin/bash

    - name: Start Django project
      shell: python3 manage.py runserver 0.0.0.0:8000
      args:
        chdir: /var/www/DjangoProject
        