---
- name: Deploy local Django app to remote Ubuntu server
  hosts: webservers
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Python and required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Create app directory
      file:
        path: "{{ app_remote_path }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy app files to server
      copy:
        src: "{{ app_local_path }}/"
        dest: "{{ app_remote_path }}/"
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create virtual environment
      command: python3 -m venv {{ app_remote_path }}/venv
      args:
        creates: "{{ app_remote_path }}/venv"

    - name: Install Django in virtual environment
      shell: |
        source {{ app_remote_path }}/venv/bin/activate
        pip install --upgrade pip
        pip install django
      args:
        executable: /bin/bash

    - name: Start Django development server (not for production)
      shell: |
        source {{ app_remote_path }}/venv/bin/activate
        nohup python manage.py runserver 0.0.0.0:8000 &
      args:
        chdir: "{{ app_remote_path }}"
        executable: /bin/bash
